export const GET_PRODUCT = "GET_PRODUCT";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FILTER_PRODUCTS_BY_TITLE = "FILTER_PRODUCTS_BY_TITLE";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";